CREATE TABLE IF NOT EXISTS comments (
  id SERIAL PRIMARY KEY,
  path VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_comments_path ON comments(path);
